// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4FV5OXANuYAAWvIVbfWPloj06eNWQYi0',
    appId: '1:314832835671:web:0ba69f376783cca5e77f12',
    messagingSenderId: '314832835671',
    projectId: 'senergy-e43a7',
    authDomain: 'senergy-e43a7.firebaseapp.com',
    storageBucket: 'senergy-e43a7.appspot.com',
    measurementId: 'G-DFEMFFKDD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLAXazrj5Ru5hayJEdtMcLkNZHG-EV2w',
    appId: '1:314832835671:android:e9882e485273b09ae77f12',
    messagingSenderId: '314832835671',
    projectId: 'senergy-e43a7',
    storageBucket: 'senergy-e43a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWf5GzmJEPzRPiMha0ac_aYudZx2gXaA',
    appId: '1:314832835671:ios:82d0663f90a1d680e77f12',
    messagingSenderId: '314832835671',
    projectId: 'senergy-e43a7',
    storageBucket: 'senergy-e43a7.appspot.com',
    iosClientId: '314832835671-2u7j6mt5e5odt0mp1jj1ss1j1dugqdea.apps.googleusercontent.com',
    iosBundleId: 'com.example.senergy',
  );
}
